name: workshop-itn-potsdam-2023-01
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - dask
  - xarray
  - xarray-simlab=0.5.0
  - netcdf4
  - fastscapelib-f2py=2.8.3
  - ipyfastscape
  - jupyterlab>=3
  - ipykernel
  - ipyleaflet
  - ipython
  - matplotlib-base
  - graphviz
  - python-graphviz
  - hvplot=0.7.0
  - numba
  - ipywidgets
  - hvplot
  - zarr
  - tqdm
  - scipy
  - nomkl
  - pip
  - pip:
      - git+https://github.com/ARM-software/mango.git
      - git+https://github.com/fastscape-lem/fastscape
